#!/usr/bin/env node
/**
 * NiteVelour static build:
 * - Builds homepage, live directory, category hubs, guides, and legal pages
 * - Optionally builds static model profile pages from data/performers.json (generated by npm run sync:models)
 *
 * Notes:
 * - Keep your Crak API secrets ONLY in Cloudflare Pages env vars and/or local .env for sync scripts.
 * - This build script never needs your API key/token.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

function readJSON(relPath) {
  const p = path.join(ROOT, relPath);
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function ensureDir(relDir) {
  fs.mkdirSync(path.join(ROOT, relDir), { recursive: true });
}

// Remove a directory/file if it exists (recursive). Used to guarantee clean builds.
function rimraf(relPath) {
  fs.rmSync(path.join(ROOT, relPath), { recursive: true, force: true });
}

function writeFile(relPath, content) {
  const abs = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, "utf8");
}

function esc(s = "") {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function slugify(s = "") {
  const out = String(s).toLowerCase().trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return out || "profile";
}

function safeId(s = "") {
  return String(s).trim().replace(/[^a-zA-Z0-9_-]+/g, "-");
}

function brandKeyFrom(perf) {
  const item = (perf?.itemId || "").toLowerCase();
  const sys = (perf?.systemSource || "").toLowerCase();
  const prefix = item.includes("_") ? item.split("_")[0] : "";
  return (prefix || sys || "cams").replace(/[^a-z0-9_-]/g, "");
}

function brandLabel(key) {
  const k = (key || "").toLowerCase();
  if (k === "awempire") return "LiveJasmin";
  if (k === "streamate") return "Jerkmate";
  if (k === "stripchat") return "Stripchat";
  if (k === "chaturbate") return "Chaturbate";
  return key ? key[0].toUpperCase() + key.slice(1) : "Cams";
}

function canonicalUrl(domain, pathOnly) {
  return (domain || "").replace(/\/+$/,"") + pathOnly;
}

function navHTML(cfg) {
  return `
<header style="border-bottom:1px solid #222233;background:#0b0b10;">
  <div style="max-width:1080px;margin:0 auto;padding:14px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;">
    <div style="display:flex;align-items:baseline;gap:10px;">
      <a href="/" style="color:#fff;text-decoration:none;font:700 18px system-ui;">${esc(cfg.siteName || "NiteVelour")}</a>
      <span style="color:#a9a9c2;font:500 12px system-ui;">${esc(cfg.brandTagline || "")}</span>
    </div>
    <nav style="display:flex;gap:12px;align-items:center;flex-wrap:wrap;">
      <a href="/live/" style="color:#cfcfe6;text-decoration:none;font:600 13px system-ui;">Live Now</a>
      <a href="/cams/" style="color:#cfcfe6;text-decoration:none;font:600 13px system-ui;">Cams</a>
      <a href="/platforms/" style="color:#cfcfe6;text-decoration:none;font:600 13px system-ui;">Platforms</a>
      <a href="/categories/" style="color:#cfcfe6;text-decoration:none;font:600 13px system-ui;">Categories</a>
      <a href="/guides/" style="color:#cfcfe6;text-decoration:none;font:600 13px system-ui;">Guides</a>
      <a href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=nav")}" style="color:#0b0b10;background:#6a5acd;border-radius:10px;padding:9px 12px;text-decoration:none;font:800 13px system-ui;">
        ${esc(cfg.primaryCTA?.label || "Enter")}
      </a>
    </nav>
  </div>
</header>`;
}


function footerHTML(cfg, buildStamp) {
  const links = [
    { href: "/privacy/", label: "Privacy" },
    { href: "/terms/", label: "Terms" },
    { href: "/dmca/", label: "DMCA" },
    { href: "/2257/", label: "2257" },
    { href: "/disclosure/", label: "Disclosure" },
    { href: "/contact/", label: "Contact" },
  ];
  return `
<footer style="border-top:1px solid #222233;background:#0b0b10;margin-top:40px;">
  <div style="max-width:1080px;margin:0 auto;padding:18px 16px;color:#a9a9c2;font:500 12px system-ui;">
    <div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:10px;">
      ${links.map(l => `<a href="${l.href}" style="color:#cfcfe6;text-decoration:none;">${l.label}</a>`).join("")}
    </div>

    <div>Adults only. All previews/embeds are provided by third-party partners. ${esc(cfg.siteName || "NiteVelour")} does not host any video files.</div>

    <div style="margin-top:10px;display:flex;gap:10px;flex-wrap:wrap;align-items:center;">
      <span>© ${new Date().getFullYear()} ${esc(cfg.siteName || "NiteVelour")}. All rights reserved.</span>
      <span style="opacity:.55">•</span>
      <span>No browser cryptominers / “web miners”.</span>
      <span style="opacity:.55">•</span>
      <span>Pages ship with first‑party scripts for site functionality; outbound links/embeds are third‑party.</span>
    </div>

    <div style="margin-top:10px;opacity:.6">Build: ${esc(buildStamp)}</div>
  </div>
</footer>`;
}


function ageGateJS() {
  return `
<div id="ageOverlay" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.72);z-index:9999;">
  <div style="max-width:640px;margin:10vh auto;padding:24px;border:1px solid #2a2a35;border-radius:14px;background:#12121a;">
    <h2 style="margin:0 0 10px 0;font:600 22px system-ui;">Adults only (18+)</h2>
    <p style="margin:0 0 18px 0;font:400 14px/1.5 system-ui;color:#cfcfe6;">
      This site contains adult content. By continuing, you confirm you are at least 18 years old (or the age of majority where you live).
    </p>
    <div style="display:flex;gap:10px;flex-wrap:wrap;">
      <button id="ageYes" style="padding:10px 14px;border-radius:10px;border:0;background:#6a5acd;color:#fff;font:600 14px system-ui;cursor:pointer;">
        I am 18+
      </button>
      <a href="https://www.google.com/" style="padding:10px 14px;border-radius:10px;border:1px solid #2a2a35;color:#cfcfe6;font:600 14px system-ui;text-decoration:none;">
        Leave
      </a>
    </div>
  </div>
</div>
<script>
(function(){
  try{
    var key="nv_age_ok";
    if(localStorage.getItem(key)==="1") return;
    var o=document.getElementById("ageOverlay");
    var y=document.getElementById("ageYes");
    if(!o||!y) return;
    o.style.display="block";
    y.addEventListener("click", function(){
      try{ localStorage.setItem(key,"1"); }catch(e){}
      o.style.display="none";
    });
  }catch(e){}
})();
</script>`;
}


function baseCSS() {
  return `
  <style>
    body{margin:0;background:#07070b;color:#fff}
    a{color:inherit}
    .wrap{max-width:1080px;margin:0 auto;padding:20px 16px}
    .card{background:#101018;border:1px solid #222233;border-radius:14px;padding:16px}
    .card2{background:#101018;border:1px solid #222233;border-radius:16px;padding:14px}
    .grid{display:grid;gap:12px}
    @media(min-width:900px){.cols4{grid-template-columns:repeat(4,1fr)}.cols3{grid-template-columns:repeat(3,1fr)}}
    @media(min-width:700px) and (max-width:899px){.cols4{grid-template-columns:repeat(3,1fr)}.cols3{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:699px){.cols4,.cols3{grid-template-columns:repeat(2,1fr)}}
    .muted{color:#a9a9c2}
    .btn{display:inline-block;background:#6a5acd;color:#0b0b10;border-radius:12px;padding:10px 14px;font:800 14px system-ui;text-decoration:none}
    .btn2{display:inline-block;border:1px solid #2a2a35;color:#cfcfe6;border-radius:12px;padding:10px 14px;font:800 14px system-ui;text-decoration:none;background:transparent}
    h1,h2,h3{font-family:system-ui;margin:0 0 10px 0}
    p,li{font-family:system-ui;color:#cfcfe6}
    /* Live cards / buttons */
    .thumb{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:12px;background:#000;border:1px solid rgba(255,255,255,.06);box-shadow:0 10px 28px rgba(0,0,0,.35)}
    .row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}
    .pill{padding:8px 10px;border-radius:999px;border:1px solid #2a2a35;background:#0b0b10;color:#cfcfe6;font:700 12px system-ui;cursor:pointer}
    .pillActive{background:#6a5acd;color:#0b0b10;border-color:#6a5acd}
    .title{font:800 14px system-ui}
    .mini{color:#a9a9c2;font:700 12px system-ui}
    .actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}
    .actions a.primary{background:#6a5acd;color:#0b0b10;border-radius:10px;padding:9px 12px;text-decoration:none;font:800 13px system-ui}
    .actions a.secondary{border:1px solid #2a2a35;color:#cfcfe6;border-radius:10px;padding:9px 12px;text-decoration:none;font:800 13px system-ui}
    /* Preview iframe */
    .playerLink{display:block;width:100%;height:60vh;min-height:360px;position:relative}
    .playerFrame{pointer-events:none;display:block;width:100%;height:100%;border:0;border-radius:16px;background:#000}

    /* Guides UI */
    .guidesControls{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}
    .gPill{border:1px solid #2a2a35;background:#0b0b10;color:#cfcfe6;border-radius:999px;padding:8px 10px;font:700 12px system-ui;cursor:pointer}
    .gPill:hover{border-color:#3a3a55}
    .gPill.isActive{background:rgba(106,90,205,.18);border-color:rgba(106,90,205,.55);color:#ecebff}

    /* Tile cards (use on most grids for a richer vibe) */
    .tile{position:relative;overflow:hidden;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}
    .tile:before{content:"";position:absolute;inset:-1px;background:radial-gradient(800px 260px at 20% 0%, rgba(106,90,205,.22), transparent 55%),radial-gradient(800px 260px at 80% 100%, rgba(255,77,166,.10), transparent 60%);opacity:.55;pointer-events:none}
    .tile:hover{transform:translateY(-2px);border-color:#3a3a55;box-shadow:0 18px 44px rgba(0,0,0,.34)}
    .tile > *{position:relative}
    .gCard{position:relative;overflow:hidden;display:flex;flex-direction:column;min-height:178px;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}
    .gCard:before{content:"";position:absolute;inset:-1px;background:radial-gradient(800px 260px at 20% 0%, rgba(106,90,205,.25), transparent 55%),radial-gradient(800px 260px at 80% 100%, rgba(255,77,166,.12), transparent 60%);opacity:.65;pointer-events:none}
    .gTop{position:relative;display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:6px}
    .gBadge{position:relative;display:inline-flex;align-items:center;gap:6px;border:1px solid #2a2a35;background:rgba(0,0,0,.22);border-radius:999px;padding:6px 8px;font:800 11px system-ui;letter-spacing:.02em;color:#cfcfe6}
    .gBadge.high{border-color:rgba(106,90,205,.55);background:rgba(106,90,205,.16);color:#ecebff}
    .gBadge.platform{border-color:rgba(0,204,255,.45);background:rgba(0,204,255,.10);color:#dcfbff}
    .gBadge.safety{border-color:rgba(0,255,153,.35);background:rgba(0,255,153,.10);color:#d9ffef}
    .gBadge.tips{border-color:rgba(255,204,0,.35);background:rgba(255,204,0,.10);color:#fff3cc}
    .gTitle{position:relative;font:800 15px/1.25 system-ui;letter-spacing:.01em}
    .gExcerpt{position:relative;margin-top:8px;color:#cfcfe6;font:600 13px/1.5 system-ui;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;opacity:.95}
    .gCard .actions{position:relative;margin-top:auto}
    .gCard:hover{transform:translateY(-2px);border-color:#3a3a55;box-shadow:0 18px 44px rgba(0,0,0,.34)}


  
    /* FAQ / details */
    details.faq{border:1px solid #222233;background:#0b0b10;border-radius:12px;padding:10px 12px}
    details.faq + details.faq{margin-top:10px}
    details.faq summary{cursor:pointer;font:800 13px system-ui;color:#ecebff;list-style:none}
    details.faq summary::-webkit-details-marker{display:none}
    details.faq .ans{margin-top:8px;color:#cfcfe6;font:600 13px/1.5 system-ui}
</style>`;
}


function page({ cfg, title, desc, canonicalPath, body, extraHead = "", extraJS = "", buildStamp }) {
  const fullTitle = `${esc(cfg.siteName || "NiteVelour")} — ${esc(title)}`;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="rating" content="adult">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${fullTitle}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${esc(canonicalUrl(cfg.domain || "", canonicalPath))}">
  ${baseCSS()}
  ${extraHead}
</head>
<body>
  ${navHTML(cfg)}
  ${body}
  ${footerHTML(cfg, buildStamp)}
  ${ageGateJS()}
  ${extraJS}
</body>
</html>`;
}

/** Live grid JS: fetches /api/live and renders cards. */
function liveGridJS({ defaultBrands = "", defaultGender = "", defaultTopic = "", pageSize = 24 }) {
  const brands = esc(defaultBrands);
  const gender = esc(defaultGender);
  const topicDefault = esc(defaultTopic);
  return `
<script>
(function(){
  const state = { page: 1, gender: "${gender}", brands: "${brands}", topic: "${topicDefault}", size: ${Number(pageSize) || 24} };
  const grid = document.getElementById("liveGrid");
  const moreBtn = document.getElementById("loadMore");
  const tabs = document.querySelectorAll("[data-gender]");
  const status = document.getElementById("liveStatus");

  // Allow URL params to override defaults (useful for /live/?brands=&gender=&topic=)
  try{
    const qs = new URLSearchParams(location.search);
    const qb = qs.get("brands");
    const qg = qs.get("gender");
    const qt = qs.get("topic");
    if(qb && !state.brands) state.brands = qb;
    if(qg && !state.gender) state.gender = qg;
    if(qt) state.topic = qt;
  }catch(e){}

  function brandKeyFrom(p){
    const item = (p.itemId || "").toLowerCase();
    const sys = (p.systemSource || "").toLowerCase();
    const prefix = item.includes("_") ? item.split("_")[0] : "";
    return (prefix || sys || "cams").replace(/[^a-z0-9_-]/g,"");
  }
  function safeId(s){ return String(s||"").trim().replace(/[^a-zA-Z0-9_-]+/g,"-"); }
  function profileUrl(p){
    const b = brandKeyFrom(p);
    const id = safeId(p.itemId || (b + "-" + (p.nameClean||p.name||"")));
    return "/m/" + encodeURIComponent(b) + "/" + encodeURIComponent(id) + "/";
  }

  function card(p){
    const name = p.nameClean || p.name || "Live";
    const b = brandKeyFrom(p);
    const prof = profileUrl(p);
    const watch = p.roomUrl || "/go/cams?pos=live_card";
    const thumb = p.thumbnailUrl || "";
    const live = p.live ? "Live now" : "Offline";
    return \`
      <div class="card2 tile">
        \${thumb ? \`<a href="\${prof}"><img class="thumb" src="\${thumb}" alt="\${name}"/></a>\` : ""}
        <div style="margin-top:10px">
          <div class="title">\${name}</div>
          <div class="mini">\${b} • \${live}</div>
          <div class="actions">
            <a class="secondary" href="\${prof}">Profile</a>
            <a class="primary" href="\${watch}" target="_blank" rel="nofollow sponsored noopener">Watch Live</a>
          </div>
        </div>
      </div>\`;
  }

  async function load(reset){
    if(!grid) return;
    if(reset){ state.page = 1; grid.innerHTML = ""; }
    if(status) status.textContent = "Loading…";
    const u = new URL("/api/live", location.origin);
    u.searchParams.set("page", String(state.page));
    u.searchParams.set("size", String(state.size));
    u.searchParams.set("sorting", "score");
    u.searchParams.set("live", "true");
    if(state.gender) u.searchParams.set("gender", state.gender);
    if(state.brands) u.searchParams.set("brands", state.brands);
    if(state.topic) u.searchParams.set("topic", state.topic);

    const res = await fetch(u.toString(), { headers: { "accept":"application/json" } });
    const data = await res.json().catch(()=>null);

    const list = data && Array.isArray(data.performers) ? data.performers : [];
    for(const p of list){ grid.insertAdjacentHTML("beforeend", card(p)); }
    if(status) status.textContent = list.length ? "" : "No performers found (try another filter).";
    state.page += 1;
  }

  if(moreBtn){ moreBtn.addEventListener("click", ()=>load(false)); }
  tabs.forEach(t=>{
    t.addEventListener("click", ()=>{
      tabs.forEach(x=>x.classList.remove("pillActive"));
      t.classList.add("pillActive");
      state.gender = t.getAttribute("data-gender") || "";
      load(true);
    });
  });

  load(true);
})();
</script>`;
}

function liveModuleHTML({ cfg, title = "Live Now", subtitle = "Fresh live performers (updates automatically).", defaultGender = "" }) {
  const brands = Array.isArray(cfg?.crak?.brands) ? cfg.crak.brands.join(",") : "";
  const size = (cfg?.home?.liveNow?.size ?? 24);
  const tabs = [
    { k: "", label: "All" },
    { k: "f", label: "Women" },
    { k: "t", label: "Trans" },
    { k: "c", label: "Couples" },
    { k: "m", label: "Men" },
  ];
  return {
    html: `
<section class="card">
  <h2 style="margin:0 0 6px 0">${esc(title)}</h2>
  <div class="muted">${esc(subtitle)}</div>
  <div class="row" style="margin-top:12px">
    ${tabs.map((t,i)=>`<button class="pill ${i===0?'pillActive':''}" data-gender="${t.k}">${t.label}</button>`).join("")}
    <span id="liveStatus" class="muted"></span>
    <span style="margin-left:auto"></span>
    <a class="btn2" href="/live/">Open live directory</a>
    <a class="btn" href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=live")}">Enter Live Cams</a>
  </div>
  <div id="liveGrid" class="grid cols4" style="margin-top:14px"></div>
  <div class="row" style="margin-top:14px">
    <button id="loadMore" class="btn2">Load more</button>
    <a class="btn2" href="/guides/best-live-cams/">Best Live Cams</a>
  </div>
</section>`,
    js: liveGridJS({ defaultBrands: brands, defaultGender, pageSize: size })
  };
}

/** Smaller live grid used inside guides to create a Guide → Live → Profile → Watch loop. */
function guideMiniLiveModule(cfg, slug) {
  const s = String(slug || "").toLowerCase();
  const knownBrands = ["stripchat","chaturbate","awempire","streamate","livejasmin","jerkmate"];
  let brand = "";
  for (const b of knownBrands) { if (s.includes(b)) { brand = b; break; } }

  let gender = "";
  if (s.includes("couples")) gender = "c";
  else if (s.includes("trans")) gender = "t";
  else if (s.includes("men") || s.includes("male") || s.includes("gay")) gender = "m";
  else if (s.includes("women") || s.includes("female") || s.includes("girls")) gender = "f";


  let topic = "";
  const topicMap = [
    ["bdsm","bdsm"], ["kink","bdsm"], ["fetish","fetish"], ["cosplay","cosplay"],
    ["goth","goth"], ["alt","goth"], ["milf","milf"], ["mature","mature"],
    ["latina","latina"], ["asian","asian"], ["ebony","ebony"], ["curvy","curvy"],
    ["fitness","fitness"], ["feet","feet"]
  ];
  for (const [k,v] of topicMap) { if (s.includes(k)) { topic = v; break; } }

  const brandLabelText = brand ? brandLabel(brand) : "";
  const genderLabel = (k) => ({ f:"Women", t:"Trans", c:"Couples", m:"Men" }[k] || "All");
  const topicLabel = (t) => ({ bdsm:"BDSM & kink", fetish:"Fetish", cosplay:"Cosplay", goth:"Alt / goth", milf:"MILF", mature:"Mature", latina:"Latina", asian:"Asian", ebony:"Ebony", curvy:"Curvy", fitness:"Fitness", feet:"Feet" }[t] || (t ? (t[0].toUpperCase()+t.slice(1)) : ""));
  const title = brand ? `Live now on ${brandLabelText}${topic ? " — " + topicLabel(topic) : ""}` : (topic ? `Live now — ${topicLabel(topic)}` : (gender ? `Live now — ${genderLabel(gender)}` : "Live now"));
  const subtitle = "A small live grid that updates automatically. Use Profile + Related links to keep browsing fast.";

  const params = [];
  if (brand) params.push("brands=" + encodeURIComponent(brand));
  if (gender) params.push("gender=" + encodeURIComponent(gender));
  if (topic) params.push("topic=" + encodeURIComponent(topic));
  const liveHref = "/live/" + (params.length ? "?" + params.join("&") : "");

  return {
    html: `
<section class="card" style="margin-top:14px">
  <h2 style="margin:0 0 6px 0">${esc(title)}</h2>
  <div class="muted">${esc(subtitle)}</div>
  <div id="liveStatus" class="muted" style="margin-top:10px"></div>
  <div id="liveGrid" class="grid cols4" style="margin-top:14px"></div>
  <div class="row" style="margin-top:14px">
    <a class="btn2" href="${esc(liveHref)}">Open full live directory</a>
    <a class="btn" href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=guide_live")}">Enter live cams</a>
  </div>
</section>`,
    js: liveGridJS({ defaultBrands: brand, defaultGender: gender, defaultTopic: topic, pageSize: 8 })
  };
}


/** Refresh live status + room URLs on static model profile pages, and show live alternatives when offline. */
function profileRefreshJS({ brand = "", name = "", gender = "", topic = "" }) {
  const b = JSON.stringify(String(brand || ""));
  const n = JSON.stringify(String(name || ""));
  const g = JSON.stringify(String(gender || ""));
  const t = JSON.stringify(String(topic || ""));
  return `
<script>
(function(){
  const brand = ${b};
  const name = ${n};
  const gender = ${g};
  const topic = ${t};

  const line = document.getElementById("nvLiveLine");
  const watchBtn = document.getElementById("nvWatchBtn");
  const altSection = document.getElementById("nvAltSection");
  const altStatus = document.getElementById("nvAltStatus");
  const altGrid = document.getElementById("nvAltGrid");
  const iframe = document.getElementById("nvIframe");
  const iframeLink = document.getElementById("nvIframeLink");

  const escHtml = (s) => String(s||"").replace(/[&<>"]/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;" }[c]));
  const isLive = (v) => {
    if (v === true || v === 1 || v === "1") return true;
    const s = String(v||"").toLowerCase();
    return s === "true" || s === "live";
  };

  const prefix = (() => {
    try{
      if(line && line.textContent) return line.textContent.split("•")[0].trim();
    }catch(e){}
    return brand || "";
  })();

  function setLine(txt){
    if(!line) return;
    line.textContent = (prefix ? (prefix + " • ") : "") + txt;
  }

  function safeId(x){
    return String(x||"").trim()
      .replace(/[^a-zA-Z0-9_-]+/g,"-")
      .replace(/-+/g,"-")
      .replace(/(^-|-$)/g,"");
  }

  async function fetchJSON(u){
    const res = await fetch(u, { headers: { "accept":"application/json" }, cache: "no-store" });
    return res.json().catch(() => null);
  }

  function renderAlt(list){
    if(!altSection || !altGrid) return;
    altGrid.innerHTML = "";
    altSection.style.display = "";
    if(!Array.isArray(list) || !list.length){
      if(altStatus) altStatus.textContent = "No live alternatives right now. Try the Live directory.";
      return;
    }
    if(altStatus) altStatus.textContent = "";
    list.slice(0, 8).forEach((p) => {
      try{
        const b = (p.systemSource || p.brand || "").toLowerCase() || brand || "cams";
        const id = safeId(p.itemId || "");
        const href = "/m/" + encodeURIComponent(b) + "/" + encodeURIComponent(id) + "/";
        const nm = p.nameClean || p.name || "Live";
        const thumb = p.thumbnailUrl || "";
        const watch = p.roomUrl || "/go/cams?pos=model_alt";
        altGrid.insertAdjacentHTML("beforeend",
          '<div class="card2 tile">' +
            (thumb ? ('<a href="' + href + '"><img class="thumb" src="' + escHtml(thumb) + '" alt="' + escHtml(nm) + '"/></a>') : '') +
            '<div class="title" style="margin-top:10px">' + escHtml(nm) + '</div>' +
            '<div class="mini">' + escHtml(b.toUpperCase()) + '</div>' +
            '<div class="actions"><a class="secondary" href="' + href + '">Profile</a>' +
            '<a class="primary" href="' + escHtml(watch) + '" target="_blank" rel="nofollow sponsored noopener">Watch</a></div>' +
          '</div>');
      }catch(e){}
    });
  }

  async function loadAlternatives(){
    if(!altSection || !altGrid) return;
    altSection.style.display = "none";
    if(altStatus) altStatus.textContent = "Finding live alternatives…";

    const u = new URL("/api/live", location.origin);
    u.searchParams.set("page","1");
    u.searchParams.set("size","8");
    u.searchParams.set("sorting","score");
    u.searchParams.set("live","true");
    if(brand) u.searchParams.set("brands", brand);
    if(gender) u.searchParams.set("gender", gender);
    if(topic) u.searchParams.set("topic", topic);
    u.searchParams.set("_t", String(Date.now()));

    let data = await fetchJSON(u.toString());
    let list = (data && data.ok && Array.isArray(data.performers)) ? data.performers : [];

    // If too narrow, retry without topic then without gender
    if(!list.length && topic){
      u.searchParams.delete("topic");
      u.searchParams.set("_t", String(Date.now()));
      data = await fetchJSON(u.toString());
      list = (data && data.ok && Array.isArray(data.performers)) ? data.performers : [];
    }
    if(!list.length && gender){
      u.searchParams.delete("gender");
      u.searchParams.set("_t", String(Date.now()));
      data = await fetchJSON(u.toString());
      list = (data && data.ok && Array.isArray(data.performers)) ? data.performers : [];
    }

    renderAlt(list);
  }

  async function refresh(){
    if(!brand || !name) return;
    setLine("Checking…");

    const u = new URL("/api/performer", location.origin);
    u.searchParams.set("brand", brand);
    u.searchParams.set("name", name);
    u.searchParams.set("_t", String(Date.now()));

    const data = await fetchJSON(u.toString());
    const p = (data && data.ok && data.performer) ? data.performer : null;

    if(!p){
      setLine("Offline");
      loadAlternatives();
      return;
    }

    const live = isLive(p.live);
    if(live){
      setLine("Live now");
      if(watchBtn && p.roomUrl) watchBtn.setAttribute("href", p.roomUrl);
      if(iframe && p.iframeFeedURL) iframe.setAttribute("src", p.iframeFeedURL);
      if(iframeLink && p.roomUrl) iframeLink.setAttribute("href", p.roomUrl);
      if(altSection) altSection.style.display = "none";
    } else {
      setLine("Offline");
      loadAlternatives();
    }
  }

  refresh();
  setInterval(refresh, 25000);
})();
</script>`;
}

function legalPages(cfg, buildStamp) {
  const contact = cfg.contact || {};
  const generalEmail = contact.generalEmail || "contact@nitevelour.com";
  const privacyEmail = contact.privacyEmail || generalEmail;
  const dmcaEmail = contact.dmcaEmail || "dmca@nitevelour.com";

  const privacyBody = `
<main class="wrap">
  <section class="card">
    <h1>Privacy Policy</h1>
    <p class="muted">Last updated: ${esc(buildStamp.split("T")[0])}. This is a template — adjust to your setup and jurisdiction.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>What we collect</h2>
    <ul>
      <li><b>Basic server logs</b> (IP address, user agent, requested URL, timestamp) for security and abuse prevention.</li>
      <li><b>Cookies / local storage</b> for the 18+ age gate and basic UX preferences (if enabled).</li>
      <li><b>Third‑party data</b> from ad networks and affiliate partners (they may set cookies and use tracking parameters).</li>
    </ul>

    <h2>Ads and affiliate links</h2>
    <p>
      We monetize via advertisements and affiliate links. When you click through to third‑party sites, those third parties may
      place cookies or collect data per their own policies. We do not control third‑party tracking.
    </p>

    <h2>Analytics</h2>
    <p>
      We may use privacy‑respecting analytics to understand which pages perform well. If enabled, analytics tools may collect
      aggregated usage data (e.g., page views, referrers, device type).
    </p>

    <h2>Data retention</h2>
    <p>
      Logs are retained for a limited period for security and troubleshooting. We do not intentionally collect sensitive personal data.
    </p>

    <h2>Contact</h2>
    <p>
      For privacy questions or requests, contact: <a href="mailto:${esc(privacyEmail)}">${esc(privacyEmail)}</a>.
    </p>
  </section>
</main>`;

  const termsBody = `
<main class="wrap">
  <section class="card">
    <h1>Terms of Use</h1>
    <p class="muted">Last updated: ${esc(buildStamp.split("T")[0])}. This is a template — review and adjust.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Adults only</h2>
    <p>You must be at least 18 years old (or the age of majority where you live) to use this site.</p>

    <h2>What this site is</h2>
    <p>
      ${esc(cfg.siteName || "NiteVelour")} is a directory and guide site that links to third‑party adult services and displays
      partner-provided previews/embeds. We do not host videos.
    </p>

    <h2>External links</h2>
    <p>
      Clicking through sends you to third‑party sites. Their terms and policies apply. We are not responsible for third‑party content,
      availability, pricing, or conduct.
    </p>

    <h2>Prohibited use</h2>
    <ul>
      <li>No scraping, automation abuse, or attempts to bypass rate limits.</li>
      <li>No unlawful use, harassment, threats, or violations of any applicable laws.</li>
      <li>No attempts to access our infrastructure without authorization.</li>
    </ul>

    <h2>Disclaimer</h2>
    <p>
      The site is provided “as is” without warranties. Use at your own risk.
    </p>

    <h2>Contact</h2>
    <p>General inquiries: <a href="mailto:${esc(generalEmail)}">${esc(generalEmail)}</a>.</p>
  </section>
</main>`;

  const dmcaBody = `
<main class="wrap">
  <section class="card">
    <h1>DMCA / Takedown Policy</h1>
    <p class="muted">Last updated: ${esc(buildStamp.split("T")[0])}. This is a template — adjust to your situation.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <p>
      ${esc(cfg.siteName || "NiteVelour")} is a directory that displays partner-provided previews and links to third‑party sites.
      If you believe material accessible through our site infringes your copyright, you may submit a takedown notice.
    </p>

    <h2>How to submit a notice</h2>
    <p>Email the following information to: <a href="mailto:${esc(dmcaEmail)}">${esc(dmcaEmail)}</a></p>
    <ul>
      <li>Your full legal name and electronic or physical signature.</li>
      <li>Identification of the copyrighted work you claim has been infringed.</li>
      <li>The exact URL(s) on our site where the material appears (please be specific).</li>
      <li>Your contact information (email, address, phone).</li>
      <li>A statement that you have a good-faith belief the use is not authorized.</li>
      <li>A statement, under penalty of perjury, that the information is accurate and you are the owner or authorized agent.</li>
    </ul>

    <h2>Counter-notice</h2>
    <p>
      If you believe a takedown was submitted in error, you may submit a counter-notice. We will process it in accordance with applicable law.
    </p>

    <h2>Response time</h2>
    <p>
      We aim to respond promptly, but response time can vary depending on volume and verification requirements.
    </p>
  </section>
</main>`;

  const s2257Body = `
<main class="wrap">
  <section class="card">
    <h1>18 U.S.C. § 2257 Statement</h1>
    <p class="muted">Last updated: ${esc(buildStamp.split("T")[0])}. This is informational and not legal advice.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <p>
      ${esc(cfg.siteName || "NiteVelour")} is not a producer (primary or secondary) of any content found on this site.
      We do not create, produce, host, or upload adult performances. We provide links and partner-provided previews to third‑party services.
    </p>
    <p>
      Records required under 18 U.S.C. § 2257 and related regulations are maintained by the respective third‑party content providers.
    </p>
    <p>
      If you have questions regarding compliance, contact us at <a href="mailto:${esc(generalEmail)}">${esc(generalEmail)}</a>.
    </p>
  </section>
</main>`;

  const disclosureBody = `
<main class="wrap">
  <section class="card">
    <h1>Affiliate & Advertising Disclosure</h1>
    <p class="muted">Last updated: ${esc(buildStamp.split("T")[0])}.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <p>
      ${esc(cfg.siteName || "NiteVelour")} may earn commissions when you click affiliate links or sign up / purchase on third‑party sites.
      We may also display advertisements that compensate us based on impressions and/or clicks.
    </p>
    <p>
      Prices, availability, and terms are controlled by third‑party partners and may change at any time.
    </p>
  </section>
</main>`;

  const contactBody = `
<main class="wrap">
  <section class="card">
    <h1>Contact</h1>
    <p class="muted">General: <a href="mailto:${esc(generalEmail)}">${esc(generalEmail)}</a></p>
    <p class="muted">DMCA: <a href="mailto:${esc(dmcaEmail)}">${esc(dmcaEmail)}</a></p>
    <p class="muted">Privacy: <a href="mailto:${esc(privacyEmail)}">${esc(privacyEmail)}</a></p>
    <p style="margin-top:12px">
      Please include the page URL(s) you are referring to when contacting us.
    </p>
  </section>
</main>`;

  return [
    { out: "dist/privacy/index.html", title: "Privacy Policy", desc: "How we handle data, cookies, ads, and affiliate links.", path: "/privacy/", body: privacyBody },
    { out: "dist/terms/index.html", title: "Terms of Use", desc: "Adults-only site terms and conditions.", path: "/terms/", body: termsBody },
    { out: "dist/dmca/index.html", title: "DMCA", desc: "Takedown policy and contact details.", path: "/dmca/", body: dmcaBody },
    { out: "dist/2257/index.html", title: "2257 Statement", desc: "2257 compliance statement (informational).", path: "/2257/", body: s2257Body },
    { out: "dist/disclosure/index.html", title: "Disclosure", desc: "Affiliate and advertising disclosure.", path: "/disclosure/", body: disclosureBody },
    { out: "dist/contact/index.html", title: "Contact", desc: "How to reach us.", path: "/contact/", body: contactBody },
  ];
}


const BUILTIN_GUIDES = [
  { slug: "best-live-cams", title: "Best Live Cams", intent: "high", excerpt: "Fast ways to pick a platform + get to quality Live Now rooms." },
  { slug: "new-to-cams", title: "New to live cams (starter guide)", intent: "info", excerpt: "How cams work, what to expect, and the quickest safe path to a good room." },
  { slug: "how-to-find-a-model", title: "How to find a model fast", intent: "tips", excerpt: "Filters, categories, and a repeatable workflow to find what you want quickly." },
  { slug: "privacy-and-safety", title: "Privacy & safety checklist", intent: "safety", excerpt: "Practical steps to keep your identity, device, and payments safer." },
  { slug: "tipping-and-tokens", title: "Tipping & tokens (how it works)", intent: "tips", excerpt: "What tokens are, how tipping works, and how to avoid accidental overspend." },
  { slug: "cams-vs-dating", title: "Cams vs dating (what converts best)", intent: "high", excerpt: "When to use cams, when to test dating offers, and how to keep funnels short." },
  { slug: "best-stripchat-models", title: "Best Stripchat Models", intent: "platform", excerpt: "How to find quality Stripchat rooms + categories that convert well." },
  { slug: "best-chaturbate-models", title: "Best Chaturbate Models", intent: "platform", excerpt: "Finding the best Chaturbate rooms quickly: tags, languages, and filters." },
  { slug: "best-streamate-models", title: "Best Streamate Models", intent: "platform", excerpt: "Premium / private-show oriented discovery tips and a clean path to Live Now." },
  { slug: "best-awempire-models", title: "Best AWEmpire Models", intent: "platform", excerpt: "AWEmpire basics: what it is, how to browse, and how to land in the right room." },
  { slug: "best-for-couples", title: "Best live cams for couples", intent: "high", excerpt: "Where couples typically appear and how to filter to them faster." },
  { slug: "best-for-trans", title: "Best live cams for trans creators", intent: "high", excerpt: "How to browse trans categories respectfully, fast, and safely." },
  { slug: "best-for-bdsm", title: "Best cams for BDSM & kink", intent: "high", excerpt: "Category-first discovery + etiquette and safety basics." },
  { slug: "best-for-cosplay", title: "Best cams for cosplay", intent: "high", excerpt: "How to spot cosplay tags and find consistent creators quickly." },
  { slug: "best-for-alt", title: "Best cams for alt / goth vibes", intent: "high", excerpt: "Alt categories, tags, and a quick workflow to find the right rooms." },
  { slug: "best-for-milf", title: "Best cams for MILF / mature", intent: "high", excerpt: "Mature categories and how to filter to them faster on each platform." },
  { slug: "best-for-curvy", title: "Best cams for curvy creators", intent: "high", excerpt: "Category browsing that avoids wasting time: filters + quick checks." },
  { slug: "best-for-fitness", title: "Best cams for fitness creators", intent: "high", excerpt: "Fitness tags, categories, and a quick loop to find live rooms." },
  { slug: "best-for-latina", title: "Best cams for Latina creators", intent: "high", excerpt: "How to use tags and categories to find Latina creators fast." },
  { slug: "best-for-asian", title: "Best cams for Asian creators", intent: "high", excerpt: "Tags, categories, and safe browsing tips for Asian creator pages." },
  { slug: "watching-on-a-budget", title: "Watching on a budget", intent: "tips", excerpt: "How to browse without overspending and keep things within your limits." },
  { slug: "avoiding-scams", title: "Avoiding scams & fake links", intent: "safety", excerpt: "Red flags, safe clicking habits, and where to keep payment activity." },
  { slug: "device-and-browser-setup", title: "Device & browser setup", intent: "safety", excerpt: "Simple settings for privacy, performance, and fewer surprises." },
  { slug: "private-show-etiquette", title: "Private show etiquette", intent: "info", excerpt: "How to be respectful, get better experiences, and avoid misunderstandings." },
  { slug: "platforms-comparison", title: "Platforms comparison", intent: "high", excerpt: "Quick comparison of the main platforms and when each tends to convert best." },
  { slug: "common-terms-glossary", title: "Common terms glossary", intent: "tips", excerpt: "Quick glossary of common room terms, goals, and features." },
  { slug: "account-security", title: "Account security & 2FA", intent: "safety", excerpt: "Keep logins and accounts safer with simple, practical steps." },
  { slug: "payment-privacy", title: "Payments, billing & privacy", intent: "safety", excerpt: "How billing works, charge hygiene, and privacy-friendly habits." },
  { slug: "token-pricing-explained", title: "Tokens & pricing explained", intent: "tips", excerpt: "What tokens/credits are, pricing patterns, and budgeting tactics." },
  { slug: "how-room-goals-work", title: "How room goals work", intent: "tips", excerpt: "Understand goals/menus so you don’t get baited into overspending." },
  { slug: "reporting-and-blocking", title: "Reporting & blocking", intent: "safety", excerpt: "How to block/report bad actors and keep your browsing cleaner." },
  { slug: "bookmarking-favorites", title: "Bookmarking favorites", intent: "tips", excerpt: "How to build a favorites list so you can return fast." },
];

function getAllGuides(cfg) {
  const cfgGuides = Array.isArray(cfg.guides) ? cfg.guides : [];
  const allowBuiltins = !(cfg && cfg.seo && cfg.seo.builtinGuides === false);
  const raw = allowBuiltins ? [...cfgGuides, ...BUILTIN_GUIDES] : [...cfgGuides];

  const seen = new Set();
  const out = [];
  for (const g of raw) {
    if (!g || !g.slug) continue;
    const slug = String(g.slug).trim();
    if (!slug || seen.has(slug)) continue;
    seen.add(slug);

    const title = g.title || slug;
    const intent = String(g.intent || "info").toLowerCase();
    const baseTags = Array.isArray(g.tags) ? g.tags.map(x => String(x).toLowerCase()) : [];
    const tags = Array.from(new Set([...guideTags(slug, intent, title), ...baseTags]));

    out.push({
      slug,
      title,
      intent,
      tags,
      excerpt: g.excerpt || ""
    });
  }
  return out;
}

function guideBadge(intent) {
  const i = String(intent || "info").toLowerCase();
  if (i === "high") return { label: "High intent", cls: "high" };
  if (i === "platform") return { label: "Platform", cls: "platform" };
  if (i === "safety") return { label: "Safety", cls: "safety" };
  if (i === "tips") return { label: "Tips", cls: "tips" };
  return { label: "Guide", cls: "" };
}

function defaultGuideExcerpt(g) {
  const i = String(g.intent || "info").toLowerCase();
  if (i === "high") return "Fast routes to Live Now rooms + categories that tend to convert well.";
  if (i === "platform") return "Platform-specific browsing tips and a clean path into official rooms.";
  if (i === "safety") return "Practical steps to browse safer and avoid common mistakes.";
  if (i === "tips") return "Tactics for finding what you want faster and improving the experience.";
  return "Useful, practical info with direct paths to Live Now rooms.";
}
function guideTags(slug, intent, title) {
  const s = String(slug || "").toLowerCase();
  const t = String(title || "").toLowerCase();
  const i = String(intent || "info").toLowerCase();
  const tags = new Set();

  // intent buckets
  if (i === "high") tags.add("high");
  if (i === "tips") tags.add("tips");
  if (i === "safety") tags.add("safety");
  if (i === "platform") tags.add("platform");

  // platform-ish slugs
  if (/(stripchat|chaturbate|awempire|streamate|livejasmin|jerkmate)/.test(s) || s.includes("platform")) {
    tags.add("platform");
  }

  // tips-ish slugs
  if (/(find|search|filters?|browse|tip|tokens?|pricing|budget|setup|device|browser|bookmarks?|favorites?|quality)/.test(s + " " + t)) {
    tags.add("tips");
  }

  // safety-ish slugs
  if (/(safe|safety|privacy|scam|imperson|security|2fa|billing|payment|report)/.test(s + " " + t)) {
    tags.add("safety");
  }

  // keep at least one tag for filtering
  if (tags.size === 0) tags.add("info");
  return Array.from(tags);
}


function pickRelatedGuides(guides, currentSlug, n = 6) {
  const current = guides.find(g => g.slug === currentSlug);
  const intent = current ? String(current.intent || "info") : "info";
  const pool = guides.filter(g => g.slug !== currentSlug);
  const same = pool.filter(g => String(g.intent || "info") === intent);
  const other = pool.filter(g => String(g.intent || "info") !== intent);
  const take = (arr, k) => arr.slice(0, Math.max(0, k));
  const out = [...take(same, n), ...take(other, n)];
  return out.slice(0, n);
}


function guideExtraSections({ slug, title, tags, brand, brandName, catLabel, primary, dating }) {
  const s = String(slug || "").toLowerCase();

  const budgetHint = (s.includes("budget") || s.includes("token") || s.includes("pricing")) ?
    "If you plan to spend, set a hard cap before you enter a room." :
    "If you plan to spend, decide your cap before you enter a room.";

  const platformTitle = brand ? `${brandName} tips` : "Platform-specific tips";

  const catLine = catLabel ? `<li><b>${esc(catLabel)}</b>: use category hubs and tags first, then branch via Related profiles.</li>` : "";

  const platformLines = brand ? `
    <li>Start on <b>${esc(brandName)}</b> Live Now, then open a profile before you click Watch.</li>
    <li>Prefer rooms with clear menus/goals and stable video/audio.</li>
    <li>Bookmark a few profiles you like so you can return quickly.</li>
  ` : `
    <li>Pick 1–2 platforms per session so you don’t bounce endlessly.</li>
    <li>Use platform hubs when you already know the vibe you want.</li>
    <li>Use profiles + Related links to hop creators efficiently.</li>
  `;

  return `
    <div style="height:1px;background:#222233;margin:18px 0"></div>

    <h2>Fast start checklist</h2>
    <ul>
      <li>Open <a href="/live/">Live Now</a> and set your brand + gender filters.</li>
      <li>Open <b>Profile</b> first to confirm tags and see related creators.</li>
      <li>Keep your loop short: filter → profile → watch.</li>
      <li>${esc(budgetHint)}</li>
      ${catLine}
    </ul>

    <h2>Privacy + safety</h2>
    <ul>
      <li>Don’t share real-world identifiers (full name, city, employer, socials).</li>
      <li>Use a separate email for adult accounts; consider a dedicated browser profile.</li>
      <li>Keep your browser updated and avoid sketchy “premium/unlock” downloads.</li>
      <li>Use on-platform payments and read the billing model before buying credits.</li>
    </ul>

    <h2>${esc(platformTitle)}</h2>
    <ul>
      ${platformLines}
    </ul>

    <h2>FAQ</h2>
    <details class="faq">
      <summary>Why do some models show offline when I click through?</summary>
      <div class="ans">Live status changes fast. The directory and profiles are refreshed regularly, but performers can go offline any time between refreshes. If a room is offline, use <b>Related</b> or go back to <a href="/live/">Live Now</a>.</div>
    </details>
    <details class="faq">
      <summary>Do you host videos?</summary>
      <div class="ans">No. This site is an adults-only affiliate directory. Previews and rooms are provided by third-party partners; outbound links open the official room in a new tab.</div>
    </details>
    <details class="faq">
      <summary>How do I keep sessions private?</summary>
      <div class="ans">Use a dedicated browser profile, avoid logging into personal accounts in the same session, and keep payments on-platform. Don’t share personal info in chat.</div>
    </details>
    <details class="faq">
      <summary>Why do links open in a new tab?</summary>
      <div class="ans">So your place in the directory doesn’t get lost. You can close the room tab and keep browsing from where you left off.</div>
    </details>

    <div class="row" style="margin-top:14px">
      <a class="btn2" href="${esc(dating)}">Try dating offers</a>
      <a class="btn" href="${esc(primary)}">Enter live cams</a>
    </div>
  `;
}

function guideContent(slug, cfg, guide) {
  // Practical, conversion-oriented, non-explicit content.
  slug = String(slug || "").trim();

  // Aliases (keep old slugs working if config links differ)
  if (slug === "privacy-and-safety") slug = "how-to-stay-safe";
  if (slug === "tipping-and-tokens") slug = "how-to-tip";

  const title = (guide && guide.title) ? String(guide.title) : slug.replace(/[-_]+/g, " ").replace(/\b\w/g, c => c.toUpperCase());
  const tags = (guide && Array.isArray(guide.tags)) ? guide.tags : guideTags(slug, (guide && guide.intent) ? guide.intent : "info", title);

  const primary = (cfg && cfg.primaryCTA && cfg.primaryCTA.href) ? cfg.primaryCTA.href : "/go/cams?pos=guide";
  const dating = (cfg && cfg.secondaryCTA && cfg.secondaryCTA.href) ? cfg.secondaryCTA.href : "/go/dating?pos=guide";

  const knownBrands = ["stripchat","chaturbate","awempire","streamate","livejasmin","jerkmate"];
  let brand = "";
  for (const b of knownBrands) {
    if (String(slug).toLowerCase().includes(b)) { brand = b; break; }
  }
  const brandName = brand ? brandLabel(brand) : "";
  const liveHref = brand ? `/live/?brands=${encodeURIComponent(brand)}` : "/live/";
  const platformHref = brand ? `/platforms/${encodeURIComponent(brand)}/` : "/platforms/";

  // Category-ish hints from slug
  const catMap = [
    ["couples","Couples"], ["trans","Trans"], ["bdsm","BDSM & kink"], ["cosplay","Cosplay"],
    ["alt","Alt / goth"], ["goth","Alt / goth"], ["milf","Mature"], ["mature","Mature"],
    ["curvy","Curvy"], ["fitness","Fitness"], ["latina","Latina"]
  ];
  let catLabel = "";
  for (const [k,v] of catMap) { if (String(slug).toLowerCase().includes(k)) { catLabel = v; break; } }


  const extras = guideExtraSections({ slug, title, tags, brand, brandName, catLabel, primary, dating });
  const wrap = (html) => String(html || "") + extras;

  const blocks = {
    "best-live-cams": `
      <p>This page is built for speed: pick a platform, jump into Live Now, then use profiles + related links to find what you want with minimal friction.</p>
      <h2>Fast path</h2>
      <ol>
        <li>Open Live Now and set your filters (brands + gender).</li>
        <li>Click <b>Profile</b> for quick context and related creators.</li>
        <li>Use <b>Watch Live</b> only when you’re ready to commit.</li>
      </ol>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/?brands=stripchat,chaturbate,awempire,streamate">Open Live Now</a>
        <a class="btn2" href="/platforms/">Platforms</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
      </div>
    `,
    "new-to-cams": `
      <p>Live cam sites are basically a stream + chat + tipping system. The simplest way to start is: browse public rooms first, then decide if you want paid features.</p>
      <h2>What to expect</h2>
      <ul>
        <li><b>Public room</b>: anyone can watch; tips can trigger actions or goals.</li>
        <li><b>Private show</b>: 1:1 or small group; usually paid per minute.</li>
        <li><b>Tokens/credits</b>: the common “unit” for tips and some premium actions.</li>
      </ul>
      <h2>Starter checklist</h2>
      <ul>
        <li>Use a modern browser, block third‑party popups, and avoid sharing personal info.</li>
        <li>Start with categories/tags, not with random scrolling.</li>
        <li>Bookmark a few favorites so you can return quickly.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
        <a class="btn2" href="/guides/how-to-tip/">Tipping</a>
      </div>
    `,
    "how-to-find-a-model": `
      <p>Stop scrolling and use a repeatable workflow. This is the fastest loop for finding good rooms that match your preferences.</p>
      <h2>The 60‑second workflow</h2>
      <ol>
        <li>Choose 1–2 platforms and a gender filter.</li>
        <li>Scan thumbnails for live status and stream quality.</li>
        <li>Open <b>Profile</b> first: check tags + related creators.</li>
        <li>Click <b>Watch Live</b> when you’re ready.</li>
      </ol>
      <h2>Filters that matter</h2>
      <ul>
        <li><b>Language/timezone</b> (reduces dead rooms)</li>
        <li><b>Category first</b> (couples, cosplay, kink, etc.)</li>
        <li><b>Platform</b> (vibe + pricing model differs)</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/categories/">Categories</a>
        <a class="btn2" href="/guides/device-and-browser-setup/">Setup</a>
      </div>
    `,
    "how-to-stay-safe": `
      <p>This is a practical checklist to reduce risk while browsing adult sites: identity, device, and payment hygiene.</p>
      <h2>Identity + privacy</h2>
      <ul>
        <li>Don’t share your real name, employer, city, or social handles.</li>
        <li>Use a separate email for adult accounts.</li>
        <li>Consider a VPN if it’s legal where you are.</li>
      </ul>
      <h2>Device hygiene</h2>
      <ul>
        <li>Keep your browser updated.</li>
        <li>Disable shady extensions; avoid “free premium” tools.</li>
        <li>Use a content blocker you trust (ads are handled separately).</li>
      </ul>
      <h2>Payment hygiene</h2>
      <ul>
        <li>Understand the billing model before buying tokens/credits.</li>
        <li>Set a hard cap. Don’t chase goals when you’re tired.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/payment-privacy/">Billing & privacy</a>
      </div>
    `,
    "avoiding-scams": `
      <p>Adult traffic attracts impersonators. The safest approach is: use official room links, avoid off-site “payment requests,” and trust your instincts.</p>
      <h2>Common scam patterns</h2>
      <ul>
        <li>“Pay me off-platform” requests or fake escrow.</li>
        <li>Impersonation accounts using copied photos or names.</li>
        <li>Pressure tactics: urgent DMs, “last chance,” or guilt plays.</li>
      </ul>
      <h2>Safe habits</h2>
      <ul>
        <li>Only use official platform links from this site.</li>
        <li>Don’t download “verification” files.</li>
        <li>If something feels off, leave the room.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/account-security/">Account security</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
      </div>
    `,
    "device-and-browser-setup": `
      <p>Better setup means fewer popups, smoother streams, and fewer accidental clicks.</p>
      <h2>Recommended baseline</h2>
      <ul>
        <li>Use a modern browser and keep it updated.</li>
        <li>Enable “ask before autoplay” if you prefer manual control.</li>
        <li>Keep only trusted extensions installed.</li>
      </ul>
      <h2>Performance tips</h2>
      <ul>
        <li>Close extra tabs.</li>
        <li>If your connection is weak, reduce resolution first.</li>
        <li>Use private windows for quick sessions (less cross-site clutter).</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/watching-on-a-budget/">Budget</a>
      </div>
    `,
    "how-to-tip": `
      <p>Tipping is how most public rooms work. The key is to be intentional so you don’t overspend or get manipulated by hype.</p>
      <h2>Basic rules</h2>
      <ul>
        <li>Set a cap <b>before</b> buying tokens/credits.</li>
        <li>Tip for specific outcomes you understand.</li>
        <li>Don’t chase goals when you’re tired or frustrated.</li>
      </ul>
      <h2>Good tipping habits</h2>
      <ul>
        <li>Start small; observe the room’s “economy.”</li>
        <li>Prefer creators with clear menus/goals.</li>
        <li>If you tip, do it intentionally and within your cap.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/token-pricing-explained/">Tokens & pricing</a>
      </div>
    `,
    "private-show-etiquette": `
      <p>Private shows vary by platform. The simplest rule: be clear, respectful, and keep expectations realistic.</p>
      <h2>Before you start</h2>
      <ul>
        <li>Know the billing model (per minute, credits, etc.).</li>
        <li>Confirm your budget cap.</li>
        <li>Keep communication clear and brief.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
      </div>
    `,
    "watching-on-a-budget": `
      <p>You can enjoy cams without overspending. Use public rooms first, set caps, and pick platforms that match your spending style.</p>
      <h2>Budget tactics</h2>
      <ul>
        <li>Watch public rooms first; don’t jump into paid modes immediately.</li>
        <li>Set a hard cap for tokens/credits.</li>
        <li>Save favorites and rotate — don’t chase one room all night.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/token-pricing-explained/">Tokens & pricing</a>
      </div>
    `,
    "cams-vs-dating": `
      <p>Cams and dating offers convert differently. Cams are immediate; dating funnels need patience and usually more steps.</p>
      <h2>Use cams when…</h2>
      <ul>
        <li>You want instant gratification and quick session loops.</li>
        <li>You want a short “click → watch” path.</li>
      </ul>
      <h2>Test dating when…</h2>
      <ul>
        <li>You’re optimizing lead quality over speed.</li>
        <li>You want to try alternate monetization paths.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="${primary}">Open Live Now</a>
        <a class="btn2" href="${dating}">Try dating</a>
      </div>
    `,
    "platforms-comparison": `
      <p>This page is a quick comparison of the main platforms you’re using. Use it to pick the right “lane” for the session you want.</p>
      <h2>Fast comparison</h2>
      <ul>
        <li><b>Stripchat</b>: broad variety + fast discovery loops.</li>
        <li><b>Chaturbate</b>: tag-heavy discovery; great for browsing variety quickly.</li>
        <li><b>Streamate / Jerkmate</b>: tends to be more private-show oriented; fewer wasted clicks if you’re ready to commit.</li>
        <li><b>AWEmpire / LiveJasmin</b>: premium feel; strong “enter room” funnels.</li>
      </ul>
      <h2>How to choose (30 seconds)</h2>
      <ol>
        <li>Want variety + fast browsing? Start Stripchat/Chaturbate.</li>
        <li>Want paid/private focus? Start Streamate.</li>
        <li>Want premium vibe? Start AWEmpire.</li>
      </ol>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/platforms/">Open Platforms</a>
        <a class="btn2" href="/live/?brands=stripchat,chaturbate,awempire,streamate">Open Live Now</a>
      </div>
    `,
    "common-terms-glossary": `
      <p>A quick glossary of terms you’ll see in rooms and profiles. These aren’t universal, but they cover the common patterns.</p>
      <h2>Common terms</h2>
      <ul>
        <li><b>Tokens/Credits</b>: the unit used for tips or paid features.</li>
        <li><b>Goals</b>: a target amount of tokens to reach an event/scene.</li>
        <li><b>Menu</b>: list of actions with token prices.</li>
        <li><b>Private</b>: paid session mode (often billed per minute).</li>
        <li><b>PM/DM</b>: private message (may or may not be paid).</li>
        <li><b>VIP</b>: paid membership tier with perks.</li>
      </ul>
      <h2>How to use this</h2>
      <ul>
        <li>Before spending, confirm the room’s pricing model.</li>
        <li>Use menus/goals as “signals” for room clarity.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/token-pricing-explained/">Tokens & pricing</a>
      </div>
    `,
    "how-room-goals-work": `
      <p>Room goals and menus can be fun, but they’re also the easiest way to overspend if you don’t understand the pattern.</p>
      <h2>Goals vs menus</h2>
      <ul>
        <li><b>Menu</b> = explicit price list. Good signal.</li>
        <li><b>Goal</b> = target amount. Can be vague; read carefully.</li>
      </ul>
      <h2>Safe spending rules</h2>
      <ul>
        <li>Set a cap before buying tokens/credits.</li>
        <li>Don’t chase goals when you’re tired or frustrated.</li>
        <li>Prefer rooms with clear, consistent pricing.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/watching-on-a-budget/">Budget</a>
      </div>
    `,
    "reporting-and-blocking": `
      <p>Use block/report tools aggressively. It improves your browsing experience and reduces exposure to scams.</p>
      <h2>When to block</h2>
      <ul>
        <li>Harassment or spam DMs.</li>
        <li>Impersonation / “pay off-platform” requests.</li>
        <li>Anything that feels manipulative or unsafe.</li>
      </ul>
      <h2>Keep your loop clean</h2>
      <ul>
        <li>Stick to official room links.</li>
        <li>Don’t download “verification” files.</li>
      </ul>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/avoiding-scams/">Avoiding scams</a>
      </div>
    `,
    "bookmarking-favorites": `
      <p>The fastest way to improve your experience is to build a small favorites list and revisit it instead of starting from scratch every session.</p>
      <h2>Simple routine</h2>
      <ol>
        <li>When you find a good room, open Profile.</li>
        <li>Save the profile URL (bookmark).</li>
        <li>Next session: start from your bookmarks → then branch out via Related.</li>
      </ol>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/">Open Live Now</a>
        <a class="btn2" href="/guides/how-to-find-a-model/">Find fast</a>
      </div>
    `,
  };

  if (blocks[slug]) return wrap(blocks[slug]);

  // ---- auto-generated guide templates ----

  // Platform guide
  if (slug.endsWith("-guide") && brand) {
    return wrap(`
      <p><b>${esc(brandName || title)}</b> is one of the platforms in your rotation. This guide focuses on fast browsing, cleaner clicks, and a short path into official live rooms.</p>

      <h2>Quick start</h2>
      <ol>
        <li>Open Live Now filtered to ${esc(brandName)}.</li>
        <li>Use <b>Profile</b> pages to check tags + related creators first.</li>
        <li>Click <b>Watch Live</b> when you’re ready to enter the room.</li>
      </ol>

      <h2>What works well on this platform</h2>
      <ul>
        <li><b>Category-first discovery</b> to avoid endless scrolling.</li>
        <li><b>Consistent favorites</b> (bookmark rooms that match your vibe).</li>
        <li><b>Budget control</b>: set a cap before buying tokens/credits.</li>
      </ul>

      <h2>Where to click next</h2>
      <div class="row" style="margin-top:10px">
        <a class="btn" href="${esc(liveHref)}">Open ${esc(brandName)} Live</a>
        <a class="btn2" href="${esc(platformHref)}">Platform page</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
        <a class="btn2" href="/guides/how-to-tip/">Tipping</a>
      </div>
    `);
  }

  // Best-of platform page
  if (slug.startsWith("best-") && slug.endsWith("-models") && brand) {
    return wrap(`
      <p>This guide is built for one job: help you find higher-quality ${esc(brandName)} rooms faster with fewer wasted clicks.</p>

      <h2>The “quality check” (30 seconds)</h2>
      <ul>
        <li><b>Stream quality</b>: stable video + clear audio.</li>
        <li><b>Room vibe</b>: clear goal/menu, not chaotic spam.</li>
        <li><b>Consistency</b>: creator seems active and responsive.</li>
      </ul>

      <h2>Fast workflow</h2>
      <ol>
        <li>Open Live Now for ${esc(brandName)}.</li>
        <li>Pick a category (or start with your preferred tags).</li>
        <li>Open Profile → use Related → then Watch.</li>
      </ol>

      <div class="row" style="margin-top:10px">
        <a class="btn" href="${esc(liveHref)}">Open ${esc(brandName)} Live</a>
        <a class="btn2" href="/guides/how-to-find-a-model/">Find fast</a>
        <a class="btn2" href="/guides/watching-on-a-budget/">Budget</a>
      </div>
    `);
  }

  // Category "best-for-..." pages
  if (slug.startsWith("best-for-") && catLabel) {
    return wrap(`
      <p>This guide helps you reach <b>${esc(catLabel)}</b> rooms faster using categories, tags, and platform selection. Keep your loop short: filter → profile → watch.</p>

      <h2>Fast path</h2>
      <ol>
        <li>Open Live Now with your preferred brands.</li>
        <li>Use category hubs and tags that match <b>${esc(catLabel)}</b>.</li>
        <li>Use Profile pages to hop Related creators quickly.</li>
      </ol>

      <h2>What to look for</h2>
      <ul>
        <li>Clear tags/labels that match your category.</li>
        <li>Stable stream quality and a consistent room vibe.</li>
        <li>Creators who are active (not a dead room).</li>
      </ul>

      <div class="row" style="margin-top:10px">
        <a class="btn" href="/live/?brands=stripchat,chaturbate,awempire,streamate">Open Live Now</a>
        <a class="btn2" href="/categories/">Categories</a>
        <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
      </div>
    `);
  }

  // Generic info/tips/safety guide template (no placeholders)
  const label = (tags.includes("safety") ? "Safety checklist" : (tags.includes("tips") ? "Tips" : "Guide"));
  return wrap(`
    <p><b>${esc(title)}</b> is a ${esc(label.toLowerCase())} page designed to be useful first and conversion‑friendly second.</p>

    <h2>Key takeaways</h2>
    <ul>
      <li>Keep your path short: filter → profile → watch.</li>
      <li>Use categories/tags to avoid random scrolling.</li>
      <li>Set a budget cap before buying tokens/credits.</li>
    </ul>

    <h2>Quick start</h2>
    <ol>
      <li>Open Live Now and apply brand + gender filters.</li>
      <li>Open a Profile page first to see related creators.</li>
      <li>Click Watch Live only when you’re ready to commit.</li>
    </ol>

    <h2>Where to click next</h2>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="/live/">Open Live Now</a>
      <a class="btn2" href="/guides/how-to-find-a-model/">Find fast</a>
      <a class="btn2" href="/guides/how-to-stay-safe/">Safety</a>
      <a class="btn2" href="/guides/how-to-tip/">Tipping</a>
    </div>
  `);
  }



function buildGuides(cfg, buildStamp) {
  const guides = getAllGuides(cfg);

  const filters = [
    { key: "all", label: "All" },
    { key: "high", label: "High intent" },
    { key: "platform", label: "Platforms" },
    { key: "tips", label: "Tips" },
    { key: "safety", label: "Safety" },
  ];

  const listHTML = `
<main class="wrap">
  <section class="card">
    <h1>Guides</h1>
    <p class="muted">Useful pages first — optimized for conversions second. Use filters to find what you need fast.</p>
    <div class="guidesControls" aria-label="Guide filters">
      ${filters.map(f => `<button class="gPill" type="button" data-gfilter="${esc(f.key)}">${esc(f.label)}</button>`).join("")}
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <div class="grid cols3 guidesGrid">
      ${guides.map(g => {
        const b = guideBadge(g.intent);
        const excerpt = g.excerpt || defaultGuideExcerpt(g);
        return `
        <div class="card2 gCard" data-intent="${esc(String(g.intent||"info").toLowerCase())}" data-tags="${esc((g.tags||[]).join(','))}">
          <div class="gTop">
            <div class="gBadge ${esc(b.cls)}">${esc(b.label)}</div>
          </div>
          <div class="title gTitle">${esc(g.title || g.slug)}</div>
          <div class="gExcerpt">${esc(excerpt)}</div>
          <div class="actions">
            <a class="secondary" href="/guides/${esc(g.slug)}/">Open</a>
            <a class="primary" href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=guides")}">Enter Live</a>
          </div>
        </div>`;
      }).join("")}
    </div>
  </section>
</main>`;

  const listJS = `
<script>
(function(){
  try{
    var btns = Array.prototype.slice.call(document.querySelectorAll("[data-gfilter]"));
    var cards = Array.prototype.slice.call(document.querySelectorAll(".gCard"));
    if(!btns.length || !cards.length) return;

    function setActive(key){
      btns.forEach(function(b){ b.classList.toggle("isActive", b.getAttribute("data-gfilter")===key); });
      cards.forEach(function(c){
        var intent = (c.getAttribute("data-intent") || "info").toLowerCase();
        var tags = (c.getAttribute("data-tags") || "").split(",").map(function(x){ return (x||"").trim().toLowerCase(); }).filter(Boolean);
        var show = (key==="all") || (tags.indexOf(key)>=0) || (key==="high" && intent==="high");
        c.style.display = show ? "" : "none";
      });
      try{ localStorage.setItem("nv_guides_filter", key); }catch(e){}
    }

    btns.forEach(function(b){
      b.addEventListener("click", function(){ setActive(b.getAttribute("data-gfilter") || "all"); });
    });

    var init = "all";
    try{ init = localStorage.getItem("nv_guides_filter") || "all"; }catch(e){}
    setActive(init);
  }catch(e){}
})();
</script>`;

  const out = [];
  out.push({
    out: "dist/guides/index.html",
    html: page({
      cfg,
      title: "Guides",
      desc: "Adults-only guides for live cams: platforms, safety, tipping, and how to find what you want faster.",
      canonicalPath: "/guides/",
      body: listHTML,
      extraJS: listJS,
      buildStamp
    })
  });

  const brands = (cfg.crak && Array.isArray(cfg.crak.brands)) ? cfg.crak.brands : [];

  for (const g of guides) {
    const slug = g.slug;
    const title = g.title || slug;
    const related = pickRelatedGuides(guides, slug, 6);
    const mini = guideMiniLiveModule(cfg, slug);

    const body = `
<main class="wrap">
  <section class="card">
    <h1>${esc(title)}</h1>
    <p class="muted">Adults-only guide. Built to be useful first, monetized second.</p>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="${esc(cfg.primaryCTA?.href || ("/go/cams?pos=guide_"+slug))}">Enter live cams</a>
      <a class="btn2" href="/guides/">More guides</a>
      <a class="btn2" href="/live/">Live Now</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    ${guideContent(slug, cfg, g)}
  </section>

  ${mini.html}

  ${brands.length ? `
  <section class="card" style="margin-top:14px">
    <h2>Platforms</h2>
    <div class="row">
      ${brands.map(b=>`<a class="pill" href="/platforms/${esc(b)}/">${esc(brandLabel(b))}</a>`).join("")}
      <a class="pill" href="/platforms/">All platforms</a>
    </div>
  </section>` : ""}

  <section class="card" style="margin-top:14px">
    <h2>Related guides</h2>
    <div class="row">
      ${related.map(r=>`<a class="pill" href="/guides/${esc(r.slug)}/">${esc(r.title)}</a>`).join("")}
      <a class="pill" href="/guides/">More…</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Browse categories</h2>
    <div class="row">
      ${(cfg.categories||[]).slice(0,10).map(c=>`<a class="pill" href="/c/${esc(c.slug)}/">${esc(c.label)}</a>`).join("")}
      <a class="pill" href="/categories/">More…</a>
    </div>
  </section>
</main>`;

    out.push({
      out: `dist/guides/${slug}/index.html`,
      html: page({
        cfg,
        title,
        desc: `Adults-only guide: ${title}.`,
        canonicalPath: `/guides/${slug}/`,
        body,
        extraJS: mini.js,
        buildStamp
      })
    });
  }

  return out;
}


function buildPlatforms(cfg, buildStamp) {
  const brands = (cfg.crak && Array.isArray(cfg.crak.brands)) ? cfg.crak.brands : [];
  const guides = getAllGuides(cfg);
  const out = [];

  const indexBody = `
<main class="wrap">
  <section class="card">
    <h1>Platforms</h1>
    <p class="muted">Browse by platform when you already know the vibe you want. Each page funnels to official rooms.</p>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="/live/">Open Live Now</a>
      <a class="btn2" href="/guides/">Guides</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <div class="grid cols3">
      ${brands.map(b => {
        const label = brandLabel(b);
        return `
        <div class="card2 gCard" data-intent="platform">
          <div class="gTop"><div class="gBadge platform">Platform</div></div>
          <div class="title gTitle">${esc(label)}</div>
          <div class="gExcerpt">Quick browse + clean path to official rooms on ${esc(label)}.</div>
          <div class="actions">
            <a class="secondary" href="/platforms/${esc(b)}/">Open</a>
            <a class="primary" href="/live/?brands=${esc(encodeURIComponent(b))}">View live</a>
          </div>
        </div>`;
      }).join("")}
    </div>
  </section>
</main>`;

  out.push({
    out: "dist/platforms/index.html",
    html: page({
      cfg,
      title: "Platforms",
      desc: "Browse live cams by platform: compare vibes, categories, and get to official rooms fast.",
      canonicalPath: "/platforms/",
      body: indexBody,
      buildStamp
    })
  });

  for (const b of brands) {
    const label = brandLabel(b);
    const related = guides.filter(g => g.intent === "platform" || g.intent === "high").slice(0, 8);

    const body = `
<main class="wrap">
  <section class="card">
    <h1>${esc(label)}</h1>
    <p class="muted">Platform hub page. Use it to filter faster, then open official rooms from performer profiles.</p>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="/live/?brands=${esc(encodeURIComponent(b))}">Browse live models</a>
      <a class="btn2" href="/guides/">Guides</a>
      <a class="btn2" href="/categories/">Categories</a>
      <a class="btn2" href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=platform_"+b)}">Enter live</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Quick tips</h2>
    <ul>
      <li>Start with <a href="/live/?brands=${esc(encodeURIComponent(b))}">Live Now</a>, then use profiles to open official rooms.</li>
      <li>Use categories when you’re not sure where to start: <a href="/categories/">Women / Couples / Men / Trans</a> + niches.</li>
      <li>For privacy, use a dedicated browser profile and keep payments on-platform. See <a href="/guides/privacy-and-safety/">privacy & safety</a>.</li>
    </ul>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Popular categories</h2>
    <div class="row">
      ${(cfg.categories||[]).slice(0,12).map(c=>`<a class="pill" href="/c/${esc(c.slug)}/">${esc(c.label)}</a>`).join("")}
      <a class="pill" href="/categories/">More…</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Related guides</h2>
    <div class="row">
      ${related.map(g=>`<a class="pill" href="/guides/${esc(g.slug)}/">${esc(g.title)}</a>`).join("")}
      <a class="pill" href="/guides/">More…</a>
    </div>
  </section>
</main>`;

    out.push({
      out: `dist/platforms/${b}/index.html`,
      html: page({
        cfg,
        title: `${label} models`,
        desc: `Browse ${label} models and open official rooms fast. Categories, tips, and related guides.`,
        canonicalPath: `/platforms/${b}/`,
        body,
        buildStamp
      })
    });
  }

  return out;
}



function buildCategories(cfg, buildStamp) {
  const categories = Array.isArray(cfg.categories) ? cfg.categories : [];
  const body = `
<main class="wrap">
  <section class="card">
    <h1>Categories</h1>
    <p class="muted">Browse curated category hubs, then jump to live performers.</p>
  </section>

  <section class="card" style="margin-top:14px">
    <div class="grid cols3">
      ${categories.map(c=>`
        <div class="card2 tile">
          <div class="title">${esc(c.label)}</div>
          <div class="mini">Curated listings and related guides for ${esc(c.label)}.</div>
          <div class="actions">
            <a class="secondary" href="/c/${esc(c.slug)}/">Browse</a>
            <a class="primary" href="/go/cams?pos=cat_${esc(c.slug)}">Live cams</a>
          </div>
        </div>`).join("")}
    </div>
  </section>
</main>`;

  const out = [];
  out.push({
    path: "/categories/",
    out: "dist/categories/index.html",
    html: page({ cfg, title: "Categories", desc: "Adult categories for browsing live cams.", canonicalPath: "/categories/", body, buildStamp })
  });

  for (const c of categories) {
    const catBody = `
<main class="wrap">
  <section class="card">
    <h1>${esc(c.label)}</h1>
    <p class="muted">Category hub: ${esc(c.label)}. Use Live Now to find performers currently online.</p>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="/live/">Open Live Now</a>
      <a class="btn2" href="/go/cams?pos=cat_${esc(c.slug)}">Enter Live Cams</a>
      <a class="btn2" href="/categories/">All categories</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Tips</h2>
    <ul>
      <li>Start with Live Now to see who is currently online.</li>
      <li>Open a Profile for preview/details, then click Watch Live.</li>
      <li>Keep payments on-platform and protect your privacy.</li>
    </ul>
    <div class="row" style="margin-top:10px">
      <a class="pill" href="/guides/how-to-stay-safe/">Staying safe</a>
      <a class="pill" href="/guides/new-to-cams/">New to cams</a>
      <a class="pill" href="/guides/how-to-tip/">How tipping works</a>
    </div>
  </section>
</main>`;
    out.push({
      path: `/c/${c.slug}/`,
      out: `dist/c/${c.slug}/index.html`,
      html: page({ cfg, title: c.label, desc: `Adult category hub: ${c.label}.`, canonicalPath: `/c/${c.slug}/`, body: catBody, buildStamp })
    });
  }

  return out;
}

function buildCamsHub(cfg, buildStamp) {
  const body = `
<main class="wrap">
  <section class="card">
    <h1>${esc(cfg.siteName || "NiteVelour")}</h1>
    <p class="muted">${esc(cfg.brandTagline || "Live cam directory and curated adult guides.")}</p>
    <div class="row" style="margin-top:12px">
      <a class="btn" href="${esc(cfg.primaryCTA?.href || "/go/cams?pos=cams")}">${esc(cfg.primaryCTA?.label || "Enter Live Cams")}</a>
      <a class="btn2" href="/live/">Live Now</a>
      <a class="btn2" href="/guides/">Start with guides</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>What’s here</h2>
    <div class="grid cols3" style="margin-top:10px">
      <div class="card2 tile">
        <div class="title">Live Now</div>
        <div class="mini">Auto-updating live performers.</div>
        <div class="actions"><a class="secondary" href="/live/">Open</a></div>
      </div>
      <div class="card2 tile">
        <div class="title">Categories</div>
        <div class="mini">Category hubs that push into Live Now.</div>
        <div class="actions"><a class="secondary" href="/categories/">Open</a></div>
      </div>
      <div class="card2 tile">
        <div class="title">Guides</div>
        <div class="mini">High-intent pages that convert.</div>
        <div class="actions"><a class="secondary" href="/guides/">Open</a></div>
      </div>
    </div>
  </section>
</main>`;
  return page({ cfg, title: "Cams", desc: "Adult cams hub: live directory, categories, guides.", canonicalPath: "/cams/", body, buildStamp });
}

function buildHome(cfg, buildStamp) {
  const live = liveModuleHTML({ cfg, title: "Live Now", subtitle: "Fresh live performers (updates automatically)." });
  const categories = Array.isArray(cfg.categories) ? cfg.categories : [];
  const topCats = categories.slice(0, 12);

  const body = `
<main class="wrap">
  ${live.html}

  <section class="card" style="margin-top:14px">
    <h2 style="margin:0 0 10px 0">Top categories</h2>
    <div class="grid cols3">
      ${topCats.map(c=>`
        <div class="card2 tile">
          <div class="title">${esc(c.label)}</div>
          <div class="mini">Curated listings and related guides for ${esc(c.label)}.</div>
          <div class="actions">
            <a class="secondary" href="/c/${esc(c.slug)}/">Browse</a>
            <a class="primary" href="/go/cams?pos=home_cat_${esc(c.slug)}">Live cams</a>
          </div>
        </div>`).join("")}
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2 style="margin:0 0 10px 0">Quick links</h2>
    <div class="grid cols3">
      <div class="card2 tile">
        <div class="title">Live Now</div>
        <div class="mini">Auto-updating live performers.</div>
        <div class="actions"><a class="secondary" href="/live/">Open</a></div>
      </div>
      <div class="card2 tile">
        <div class="title">Cams hub</div>
        <div class="mini">Entry point for all cam traffic.</div>
        <div class="actions"><a class="secondary" href="/cams/">Open</a></div>
      </div>
      <div class="card2 tile">
        <div class="title">Guides</div>
        <div class="mini">High-intent pages that convert.</div>
        <div class="actions"><a class="secondary" href="/guides/">Open</a></div>
      </div>
    </div>
  </section>
</main>`;
  return { html: page({ cfg, title: "Live Cams & Guides", desc: cfg.brandTagline || "Live cam directory and curated adult guides.", canonicalPath: "/", body, buildStamp, extraJS: live.js }), extraJS: live.js };
}

function buildLivePage(cfg, buildStamp) {
  const live = liveModuleHTML({ cfg, title: "Live Directory", subtitle: "Browse live performers. Use Profile for preview/details, then Watch Live." });
  const body = `<main class="wrap">${live.html}</main>`;
  return { html: page({ cfg, title: "Live Now", desc: "Auto-updating live performers directory.", canonicalPath: "/live/", body, buildStamp, extraJS: live.js }), extraJS: live.js };
}

function buildModelPages(cfg, buildStamp) {
  const max = Number(cfg?.seo?.modelPageMax ?? 0) || 0;
  const defaultMax = max > 0 ? max : 0;
  const maxNum = defaultMax;

  const dataPath = path.join(ROOT, "data", "performers.json");
  if (!fs.existsSync(dataPath)) {
    return { pages: [], sitemapPaths: [] };
  }
  const raw = JSON.parse(fs.readFileSync(dataPath, "utf8"));
  const performers = Array.isArray(raw.performers) ? raw.performers : [];
  const limit = (maxNum === 0) ? performers.length : Math.min(maxNum, performers.length);

  // Index by brand+gender for related links
  const byBG = new Map();
  for (const p of performers) {
    const b = brandKeyFrom(p);
    const g = (p?.characteristic?.genderCode || p?.characteristic?.gender || "").toLowerCase();
    const key = `${b}|${g}`;
    if (!byBG.has(key)) byBG.set(key, []);
    byBG.get(key).push(p);
  }

  function pickRelated(p, n=12) {
    const b = brandKeyFrom(p);
    const g = (p?.characteristic?.genderCode || p?.characteristic?.gender || "").toLowerCase();
    const key = `${b}|${g}`;
    const arr = byBG.get(key) || [];
    const out = [];
    for (let i=0; i<arr.length && out.length<n; i++) {
      const q = arr[i];
      if ((q.itemId || "") === (p.itemId || "")) continue;
      out.push(q);
    }
    return out;
  }

  const pages = [];
  const sitemapPaths = [];

  for (let i=0; i<limit; i++) {
    const p = performers[i];
    const bKey = brandKeyFrom(p);
    const bLabel = brandLabel(bKey);
    const id = safeId(p.itemId || `${bKey}-${slugify(p.nameClean || p.name)}`);
    const name = p.nameClean || p.name || "Profile";
    const age = p?.characteristic?.age ? Number(p.characteristic.age) : null;
    const langs = Array.isArray(p?.characteristic?.languages) ? p.characteristic.languages : [];
    const ethnicity = Array.isArray(p?.characteristic?.ethnicities) ? p.characteristic.ethnicities : [];
    const bodyTypes = Array.isArray(p?.characteristic?.bodyTypes) ? p.characteristic.bodyTypes : [];
    const eyes = p?.characteristic?.eyeColor || "";
    const hair = p?.characteristic?.hairColor || "";
    const ctry = p?.characteristic?.country || "";
    const thumb = p.thumbnailUrl || "";
    const watch = p.roomUrl || (cfg.primaryCTA?.href || "/go/cams?pos=model");
    const iframe = p.iframeFeedURL ? `
      <a id="nvIframeLink" class="playerLink" href="${esc(watch)}" target="_blank" rel="nofollow sponsored noopener">
        <iframe id="nvIframe" class="playerFrame" src="${esc(p.iframeFeedURL)}" frameborder="0"
          allow="autoplay; encrypted-media"
          sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"></iframe>
      </a>` : "";

    const facts = [];
    if (age) facts.push(`Age: ${age}+`);
    if (langs.length) facts.push(`Languages: ${langs.slice(0,4).map(esc).join(", ")}`);
    if (bodyTypes.length) facts.push(`Body: ${bodyTypes.slice(0,3).map(esc).join(", ")}`);
    if (ethnicity.length) facts.push(`Ethnicity: ${ethnicity.slice(0,2).map(esc).join(", ")}`);
    if (eyes) facts.push(`Eyes: ${esc(eyes)}`);
    if (hair) facts.push(`Hair: ${esc(hair)}`);
    if (ctry) facts.push(`Country: ${esc(ctry)}`);

    const related = pickRelated(p, 12);
    const relatedHTML = related.length ? `
      <section class="card" style="margin-top:14px">
        <h2>More like this</h2>
        <div class="grid cols4" style="margin-top:10px">
          ${related.map(r=>{
            const rb = brandKeyFrom(r);
            const rid = safeId(r.itemId || "");
            const rname = r.nameClean || r.name || "Profile";
            const rthumb = r.thumbnailUrl || "";
            const href = `/m/${encodeURIComponent(rb)}/${encodeURIComponent(rid)}/`;
            return `<div class="card2 tile">
              ${rthumb ? `<a href="${href}"><img class="thumb" src="${esc(rthumb)}" alt="${esc(rname)}"/></a>` : ""}
              <div style="margin-top:10px" class="title">${esc(rname)}</div>
              <div class="mini">${esc(brandLabel(rb))}</div>
              <div class="actions"><a class="secondary" href="${href}">Open</a></div>
            </div>`;
          }).join("")}
        </div>
      </section>` : "";

    const modelBody = `
<main class="wrap">
  <section class="card">
    <div class="row" style="align-items:flex-start">
      ${thumb ? `<img src="${esc(thumb)}" alt="${esc(name)}" style="width:110px;height:110px;border-radius:14px;object-fit:cover;background:#000">` : ""}
      <div style="flex:1;min-width:240px">
        <h1 style="margin:0 0 8px 0">${esc(name)}</h1>
        <div id="nvLiveLine" class="muted">${esc(bLabel)} • ${p.live ? "Live now" : "Offline"}</div>
        <div class="row" style="margin-top:10px">
          <a id="nvWatchBtn" class="btn" href="${esc(watch)}" target="_blank" rel="nofollow sponsored noopener">Watch Live</a>
          <a class="btn2" href="/live/">Back to Live Now</a>
        </div>
      </div>
    </div>
    ${facts.length ? `<div class="muted" style="margin-top:12px;line-height:1.5">${facts.map(f=>`• ${f}`).join("<br>")}</div>` : ""}
  </section>

  ${iframe ? `<section class="card" style="margin-top:14px"><h2>Preview</h2>${iframe}<div class="muted" style="margin-top:10px">Clicking the preview opens the official room.</div></section>` : ""}

  ${relatedHTML}

  <section id="nvAltSection" class="card" style="margin-top:14px;display:none">
    <h2>Live alternatives</h2>
    <div id="nvAltStatus" class="muted">Finding live alternatives…</div>
    <div id="nvAltGrid" class="grid cols4" style="margin-top:10px"></div>
    <div class="row" style="margin-top:12px">
      <a class="btn2" href="/live/">Open Live Now</a>
      <a class="btn2" href="/categories/">Browse categories</a>
    </div>
  </section>
</main>`;
    const gcode = (p?.characteristic?.genderCode || p?.characteristic?.gender || "").toLowerCase();
    const profileJS = profileRefreshJS({ brand: bKey, name, gender: gcode });

    const outPath = `dist/m/${bKey}/${id}/index.html`;
    const canonicalPath = `/m/${bKey}/${id}/`;
    const html = page({
      cfg,
      title: `${name} Live Cam`,
      desc: `Watch ${name} live on ${bLabel}. Adults only.`,
      canonicalPath,
      body: modelBody,
      extraJS: profileJS,
      buildStamp
    });

    pages.push({ outPath, html });
    sitemapPaths.push(canonicalPath);
  }

  // Build a lightweight models index page
  const modelsIndexBody = `
<main class="wrap">
  <section class="card">
    <h1>Model Profiles</h1>
    <p class="muted">Browse performer profiles on-site, then click through to the official room.</p>
    <div class="row" style="margin-top:10px">
      <a class="btn" href="/live/">Live Now</a>
      <a class="btn2" href="/categories/">Categories</a>
    </div>
  </section>

  <section class="card" style="margin-top:14px">
    <h2>Platforms</h2>
    <div class="row">
      ${(Array.isArray(cfg?.crak?.brands) ? cfg.crak.brands : ["stripchat","chaturbate","awempire","streamate"])
        .map(b=>`<a class="pill" href="/models/${esc(b)}/">${esc(brandLabel(b))}</a>`).join("")}
    </div>
    <p class="muted" style="margin-top:10px">Profiles are generated from partner-provided metadata and may change.</p>
  </section>
</main>`;
  pages.push({
    outPath: "dist/models/index.html",
    html: page({ cfg, title: "Models", desc: "Performer profile directory.", canonicalPath: "/models/", body: modelsIndexBody, buildStamp })
  });
  sitemapPaths.push("/models/");

  // Platform model lists (static top N by score as in the file order)
  const byBrand = new Map();
  for (const p of performers.slice(0, limit)) {
    const b = brandKeyFrom(p);
    if (!byBrand.has(b)) byBrand.set(b, []);
    byBrand.get(b).push(p);
  }
  for (const [b, arr] of byBrand.entries()) {
    const list = arr.slice(0, 200); // keep file count low
    const body = `
<main class="wrap">
  <section class="card">
    <h1>${esc(brandLabel(b))} Profiles</h1>
    <p class="muted">Top profiles for this platform (static). For live availability, use <a href="/live/">Live Now</a>.</p>
  </section>
  <section class="card" style="margin-top:14px">
    <div class="grid cols4">
      ${list.map(p=>{
        const id = safeId(p.itemId || "");
        const name = p.nameClean || p.name || "Profile";
        const thumb = p.thumbnailUrl || "";
        const href = `/m/${encodeURIComponent(b)}/${encodeURIComponent(id)}/`;
        return `<div class="card2 tile">
          ${thumb ? `<a href="${href}"><img class="thumb" src="${esc(thumb)}" alt="${esc(name)}"/></a>` : ""}
          <div style="margin-top:10px" class="title">${esc(name)}</div>
          <div class="actions">
            <a class="secondary" href="${href}">Profile</a>
            <a class="primary" href="${esc(p.roomUrl || cfg.primaryCTA?.href || "/go/cams?pos=models")}" target="_blank" rel="nofollow sponsored noopener">Watch</a>
          </div>
        </div>`;
      }).join("")}
    </div>
  </section>
</main>`;
    const outPath = `dist/models/${b}/index.html`;
    pages.push({
      outPath,
      html: page({ cfg, title: `${brandLabel(b)} Models`, desc: `Top profiles on ${brandLabel(b)}.`, canonicalPath: `/models/${b}/`, body, buildStamp })
    });
    sitemapPaths.push(`/models/${b}/`);
  }

  return { pages, sitemapPaths };
}

function buildSitemap(cfg, buildStamp, paths) {
  const base = (cfg.domain || "").replace(/\/+$/,"");
  const urls = paths.map(p => `${base}${p}`);
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${
    urls.map(u=>`  <url><loc>${u}</loc></url>`).join("\n")
  }\n</urlset>\n`;
  writeFile("dist/sitemap.xml", xml);
  writeFile("dist/robots.txt", `User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
}

function main() {
  const cfg = readJSON("site.config.json");
  // Always build into a clean dist/ so we don't deploy stale pages/assets.
  // This prevents mixed "old" and "new" UI across different URLs and helps avoid
  // the Cloudflare Pages 20,000-file deployment limit.
  rimraf("dist");
  ensureDir("dist");

  const buildStamp = new Date().toISOString();
  writeFile("dist/build.txt", buildStamp + "\n");

  // Home
  const home = buildHome(cfg, buildStamp);
  writeFile("dist/index.html", home.html);

  // Live + Cams hub
  writeFile("dist/live/index.html", buildLivePage(cfg, buildStamp).html);
  writeFile("dist/cams/index.html", buildCamsHub(cfg, buildStamp));

  // Categories + Guides
  const catOut = buildCategories(cfg, buildStamp);
  for (const p of catOut) writeFile(p.out, p.html);

  const guideOut = buildGuides(cfg, buildStamp);
  for (const p of guideOut) writeFile(p.out, p.html);

  const platformOut = buildPlatforms(cfg, buildStamp);
  for (const p of platformOut) writeFile(p.out, p.html);

  // Legal pages
  for (const p of legalPages(cfg, buildStamp)) {
    writeFile(p.out, page({ cfg, title: p.title, desc: p.desc, canonicalPath: p.path, body: p.body, buildStamp }));
  }

  // Optional: model pages
  const model = buildModelPages(cfg, buildStamp);
  for (const p of model.pages) writeFile(p.outPath, p.html);

  // Sitemap paths
  const basePaths = [
    "/", "/live/", "/cams/", "/categories/", "/guides/",
    "/privacy/", "/terms/", "/dmca/", "/2257/", "/disclosure/", "/contact/"
  ];
  // Include category and guide pages
  const catPaths = (Array.isArray(cfg.categories) ? cfg.categories : []).map(c => `/c/${c.slug}/`);
  const guidePaths = getAllGuides(cfg).map(g => `/guides/${g.slug}/`);
  const platformBrands = (cfg.crak && Array.isArray(cfg.crak.brands)) ? cfg.crak.brands : [];
  const platformPaths = ["/platforms/", ...platformBrands.map(b => `/platforms/${b}/`)];

  buildSitemap(cfg, buildStamp, [...basePaths, ...platformPaths, ...catPaths, ...guidePaths, ...model.sitemapPaths]);

  console.log(`[build] OK — ${buildStamp}`);
  console.log(`[build] dist/build.txt written`);
  if (model.pages.length) console.log(`[build] model pages: ${model.pages.length}`);
  else console.log(`[build] model pages: 0 (run npm run sync:models first to generate data/performers.json)`);
}

main();
